### ISSUE TITLE
Milestone 2 

### ISSUE THREAD

**Issue by everittB** [UBC-MDS/R2Py2#10]
- [x] Create survey  
- [x] Collect data  
  - [x] Upload data to private repository on [github.ubc.com](github.ubc.com`)  
    - [x]  Add teaching team as collaborators 
- [x] Perform EDA on survey results  
  - [x] Summary table  
  - [x] 4 Visualizations  
  - [x] Narrated document   
- [x] Create release, tag: `v2.0`

**Comment by everittB** [comment]
[Survey Link](https://ubc.ca1.qualtrics.com/jfe/form/SV_1TCLkrcktfT5srz)

**Comment by everittB** [comment]
[Data](https://github.ubc.ca/MDS-2018-19/DSCI_541_R2Py2_results)

**Comment by mkeyim** [comment]
Finished :)
