### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by KateJohnson** [UBC-MDS/R2Py2#20]
**EDA**
- [x] The narration of results needs more detail.
- [x] The figures are good, and I like how you compared counts of the outcome between levels of the response variable. But histograms are overused; they don’t add _that_ much to what you've already shown in the tables.
- [x] There should be at least one figure that examines confounding. Can you stratify the relationship between preferred language and first language learned by the levels of a third variable?
- [x] Based on this EDA, do you think first programming language learned affects preference for R/python? Based on your second figure, it seems maybe not. What are your overall conclusions from this EDA?

**Comment by everittB** [comment]
Addressed all the feedback in PR's: #25 , #26 , #24
