### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by mani-kohli** [UBC-MDS/R2Py2#21]
write brief, 3-5 page report (including figures and references) presenting:
- [x]     question
- [x]     methods
- [x]         survey study design
- [x]         data collection methods
- [x]         analysis methods
- [x]     results and analysis
- [x]     discussion of the results
- [x]     discussion of your survey/study design

Note:
Additional report expectations:
    Your target audience is other Data Scientists who are not familiar with your project.
    Clearly introduce the survey topic and question you were interested in answering.
    Link to your study's data and code in the methods section of your report.
    Include effective visualizations and/or tables that help communicate your findings.
    Your discussion should have 2 key focuses:
        Discussing the results and findings of your survey and analysis of the survey data.
        Discussing your survey/study design, specifically:
            what did you do well to make this study as causal as possible?
            what was not done well and how did that effect your studies conclusions?
            what would you do differently next time to improve your survey/study design and why?

- [x] Team report

**Comment by ksm45** [comment]
assigned team milestone 3

**Comment by everittB** [comment]
Complete in this pull request: #27
